### ISSUE TITLE
etc directory is incompatible with documentation

### ISSUE THREAD

**Issue by fbalak** [Tendrl/gluster-integration#133]
According to installation documentation [1] some configuration files from gluster-integration etc directory should be copied to specific directories but etc directory structure is different from what is specified in documentation.
According to documentation logging.yaml.timedrotation.sample should be located at etc/samples/logging.yaml.timedrotation.sample but it is located at etc/tendrl/gluster-integration/logging.yaml.timedrotation.sample.
According to documentation there should be etc/tendrl/tendrl.conf.sample but there is no such file.
Documentation and etc directory should be united.

[1] https://github.com/Tendrl/gluster-integration/blob/7ab5e79dc28476e777887c434c4d3485c441d195/doc/source/installation.rst

**Comment by brainfunked** [comment]
The documentation applies to source based installations. The RPM packages take care of the configuration files copying.

**Comment by sankarshanmukhopadhyay** [comment]
@brainfunked perhaps we add a cover-all note on the documentation that this is applicable to the source-based installations. Packages available via packaging routines of distributions would be using manifest files to take care of this by default.

**Comment by sankarshanmukhopadhyay** [comment]
Do we want to keep this topic open until we complete the documentation or, should we file this under documentation and close this here?

**Comment by anmolsachan** [comment]
The issue can be closed according to https://github.com/Tendrl/gluster-integration/pull/188#pullrequestreview-27981091.

**Comment by fbalak** [comment]
@anmolsachan installation.rst [1] in both `master` and `develop` branches still has incorrect paths to config files in `etc` directory.

[1] https://github.com/Tendrl/gluster-integration/blob/develop/doc/source/installation.rst

**Comment by r0h4n** [comment]
- tendrl-gluster-integration and tendrl-ceph-integration require the tendrl-node-agent to be fully functional
- Configuration for tendrl-{gluster, ceph}-integration and logging config is generated by tendrl-node-agent during CreateCluster or ImportCluster 
- Calling CreateCluster or ImportCluster should be the only way to install tendrl-{gluster, ceph}-integration so as to avoid any issues arising due to tendrl-node-agent not being present or misconfigued integration service

Which means we dont need to have a standalone install doc for tendrl-{gluster, ceph}-integration
