### ISSUE TITLE
If no volume in cluster, the locking for `volume` in state sync hangs

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#237]
The acquire of lock while state sync in `tendrl-gluster-integration` hangs if there are no volumes in the cluster.
Need a fix for the same.

**Comment by r0h4n** [comment]
The locks work via etcd dir _locks/ . Is there a race condition to acquire this lock?

**Comment by nnDarshan** [comment]
I feel the issue might be this:

* when gluster-integration process that has the volume lock currently is killed/shut down. It wont release the lock. Because of this no other gluster-integration will be able to acquire the lock or  Even if you restart the process, it wont able to get the lock. 

Solution should be to delete the locks in etcd.

**Comment by shtripat** [comment]
Thats what even I suspected. But the abrupt shutdown case should be handled while start I feel and we should remove the lock if any is etcd in that case.

**Comment by nnDarshan** [comment]
@shtripat @r0h4n @shtripat 
Have sent a fix for this issue: https://github.com/Tendrl/gluster-integration/pull/238
Please let me know what you guys think
