### ISSUE TITLE
EtcdLockExpired exception intermittent for nodes in a Gluster cluster; impacts out-of-band delete operations.

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster-integration#279]
I have 4 nodes under gluster cluster, i have checked sds sync for all nodes in cluster, problem is node sync is not happening for all nodes, sometimes 2 nodes updating all sync details but other two nodes are giving etcd.EtcdLockExpired. Both two node are always giving this exception. if i restart gluster-integration then some times 3 nodes are updating fine and one node is always giving EtcdLockExpired exception. Because of this we can't give time out for out of band delete. 

The Volume details are updated from any nodes from same cluster, so this problem is hidden till now because of this. Problem is for brick details update. Brick detail are updated node wise So all brick details will never come in etcd.

**Comment by GowthamShanmugam** [comment]
@r0h4n @nnDarshan @shtripat @nthomas-redhat @sankarshanmukhopadhyay

**Comment by GowthamShanmugam** [comment]
@nnDarshan @r0h4n @sankarshanmukhopadhyay increasing seconds in 
   lock.acquire(blocking=True,lock_ttl=200)
                    if lock.is_acquired:
                        # renewing the lock
                        lock.acquire(lock_ttl=200)

is solving problem, for 4 machines 200 seconds are ok, what about more than 10 machines?

**Comment by nnDarshan** [comment]
Myself @shtripat and @GowthamShanmugam had a discussion about a way to resolve this.

Since the ttl that we set depends on the number of nodes in the gluster cluster. Its not possible to arrive at a correct lock_ttl duration.
The ttl was introduced to avoid the issue where, a gluster_integration process is stopped while it has acquired the lock and not released it yet. This used to cause the lock held by this process for ever.

So instead of using ttl to solve the above problem, we can either: a) explicitly release the lock when we handle the SIGTERM signal in gluster_integration process OR b) Handle it during the start of gluster_integration service by removing the lock from etcd explicitly.
I feel solution a) is better.
@rohan please provide your thoughts

**Comment by shtripat** [comment]
@nnDarshan I am in favor of approach-1. Is there a way we know what all locks are held by this agent and clean those only?

**Comment by GowthamShanmugam** [comment]
@r0h4n need your suggestion

**Comment by GowthamShanmugam** [comment]
#266 is a problem because of this issue

**Comment by GowthamShanmugam** [comment]
@r0h4n @nnDarshan @shtripat 
Even we remove ttl from lock, the problem for out of band delete is, Because of lock all nodes are updating its sync details one by one so if i set ttl in save method like 200 sec but if the node can lock etcd directory after 400 sec means then all brick entry is deleted from etcd and updated again.

Again it based on number of nodes in a cluster, so i am going to compare collected brick id with etcd and i will deleted not matched ids.

this only for brick to handle out of band delete. For volume this is not required because ttl is enough.

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close this issue
