### ISSUE TITLE
Storage capacity utlisation per host

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/gluster-integration#378]
It makes sense to me that the storage utlisation for hosts which are part of a gluster should be the utlisation of the brick mount points. This information needs to be made available for every host which is part of a gluster, inside that specific cluster's namespace and that it is put there by gluster-integration.

I'm not sure how much of this is presently implemented.

@shtripat @nthomas-redhat @nnDarshan @r0h4n opinion?

**Comment by brainfunked** [comment]
Also, would it make sense to maintain cluster-specific host information inside the cluster namespace? The user interaction with the information is going to be either via volumes to hosts or hosts to bricks. There's no user interface requirement to have bricks as the entry point. Given that we also need to maintain some additional cluster specific information for hosts, would it make sense to have the bricks and other host specific information organised for a gluster via volumes and hosts?

**Comment by brainfunked** [comment]
This issue may directly affect https://github.com/Tendrl/ui/issues/534 and https://github.com/Tendrl/api/issues/249.

**Comment by nnDarshan** [comment]
@brainfunked @shtripat @nthomas-redhat @r0h4n I agree that, providing the aggregated utilization of all gluster bricks per node would help a storage admin. But I feel it is also important for a storage admin to know the utilization of other critical mount points like `/root /boot /tmp /home`etc.

**Regarding current Availability in tendrl:**
As of now we have the storage utilization of gluster bricks saved at `clusters/<cluster-id>/Bricks/all/<brick-name>/utilization`. And this is indexed from volumes by location `clusters/<cluster-name>/Volumes/<vol-id>/Bricks/subvolume0/<brick-name>`. Using this mapping UI/API can get brick details like utilization for all bricks of a volume.

Currently there is no mapping of all bricks per node. But it would be a small change in gluster-integration to add a index of brick list under all nodes in the path `/clusters/<cluster-id>/nodes/<node-id>/Bricks`. So that UI/API can map bricks per node.

**Comment by brainfunked** [comment]
> But I feel it is also important for a storage admin to know the utilization of other critical mount points like /root /boot /tmp /homeetc.

I agree. However, given that there can be many such mount points, the logical place to show them all is on a host specific details view. In a list view, where there's just one single 'storage utilisation' data point to be shown, I think it makes sense to prioritise on the root partition utilisation. OTOH, it probably makes more sense to show something like 'no system mount point exceeds a warning threshold for utilisation'. This could also be applied to the brick utilisation aggregation in the context of a cluster. I suppose it comes down to what makes sense for an administrator to see on the list view.

**Comment by r0h4n** [comment]
Is this resolved @brainfunked  ?
