### ISSUE TITLE
No alerts/notifications generated when volume and brick are almost full (and possible data discrepancy)

### ISSUE THREAD

**Issue by julienlim** [Tendrl/gluster-integration#412]
I've caused one of my bricks (brick2) to become almost full, and per Grafana it sees brick2 is almost full, which also causes the volume (vol1 of which brick2 is a member of) to almost be full.

I've attached screenshots from df, gstatus, and grafana to show that I can see this in the command line that the brick is almost full.

In looking at gstatus for vol1, it says it's 34% utilized, but Grafana says it's 96.34% utilized.

Besides conflicting values for the % utilized for vol1, I'm not seeing any notifications/alerts generated or the almost full brick and almost full volume condition that are observed (in Grafana).

df -k and gstatus -v output:
![screen shot 2017-09-12 at 3 51 39 pm](https://user-images.githubusercontent.com/5589919/30345407-f32f4648-97d2-11e7-91cd-e1cce95b280e.png)

Grafana at-a-glance dashboard:
![screen shot 2017-09-12 at 3 52 59 pm](https://user-images.githubusercontent.com/5589919/30345414-f603b6a6-97d2-11e7-957d-f74ba088b2f6.png)

Tendrl UI - Alerts / Notifications: 
![screen shot 2017-09-12 at 2 22 05 pm](https://user-images.githubusercontent.com/5589919/30345443-101b3fd2-97d3-11e7-8799-faae4e2547ad.png)

![screen shot 2017-09-12 at 3 47 59 pm](https://user-images.githubusercontent.com/5589919/30345464-206796e2-97d3-11e7-9764-8ca5646a0aa8.png)

@Tendrl/qe @Tendrl/tendrl_frontend @Tendrl/tendrl-core @mcarrano

**Comment by rishubhjain** [comment]
I require few more details to debug this issue and make appropriate changes.
The required details are as follows:
1) Errors from monitoring-integration if any in /var/log/messages.

2) Value of volume utilization in etcd and grafana.
     Volume utilization in etcd can be found under /clusters/{cluster_id}/Volumes/{volume_id}/pcnt_used

3) Value of brick utilization in etcd and grafana.
    Brick utilisation in etcd is found under clusters/{cluster_id}/Bricks/all/{node_id}/{brick_id}/utilization.

4) For how long was the brick being utilized fully.(As the utilization needs to be crossing the threshold for at-least 3 mins for grafana to generate alert.)

Also if possible could you share your instance details, I would like to loop through some details to debug this issue properly.

**Comment by GowthamShanmugam** [comment]
Please check the alerting dashboard in grafana , whether it raised alert or not

**Comment by GowthamShanmugam** [comment]
The problem what is found is node-agent will read the alerts from etcd based on alert classification, there are two types of alert classification 1. node 2. cluster. if the alert is node alert then it will read /alerting/nodes/node_id/
if the alert is cluster alerts then it will read /alerting/nodes/cluster_id, this for compare the new incoming alert with existing alert in etcd to find whether the alert in clearing alert or not. So when the alert came then node-agent will read the particular directory and compare all alert.

So the problem is when an alert is healed by ok alert then it will updated in etcd with ttl of 2 days. So when directory goes empty (all ok alerts are removed by TTL) the etcd reading logic goes wrong.

When first most alert came there will be only /alerting/ path only present, so the alert is stored in etcd without any problem.  When some alerts came and removed by ttl then the directory is /alerting/nodes/{node_id}/{empty nothing is inside}. so for the second scenario, the alert reading raises an exception. After this, no node alerts are stored in etcd. but cluster alert is stored. when cluster alert directory goes empty then there also this problem will come.
so reading logic have to modify.

**Comment by r0h4n** [comment]
@rishubhjain @GowthamShanmugam @anmolbabu Is this resolved? 

@julienlim I am going to close issues which are pending verification for more than 4 days. You can re-open if required

**Comment by mbukatov** [comment]
fyi @Tendrl/tendrl-qe
