### ISSUE TITLE
Support for third option for retaining the mixed profiling enabled for volumes

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster-integration#553]
From gluster 3.4 onwards there is going to a flag saying if profiling is enabled for a volume in `get-state` command output.
Backend needs to undergo changes to support this third option while import cluster. If this option selected during import cluster flow, the tendrl should retain the mixed profiling enabled state for the individual volumes and mark the cluster level profiling enabled information as `mixed`.

Also backend should be backward compatible which makes sure, even if we dont have `get-state` returning profile info a volume level, leave the cluster as is and don't mark for individual volumes.

@r0h4n @julienlim @jjkabrown1 @nthomas-redhat comments, suggestions?

**Comment by julienlim** [comment]
@shtripat Ack on backend needing to undergo changes to support Gluster 3.4 get-state support for a profiling flag.

Re: backward compatibility, i.e. < Gluster 3.4, if volume profiling option (radio button in UI) set to "mixed" (leave as-is), I agree that we leave cluster as-is and not make any volume profiling changes.

**Comment by nthomas-redhat** [comment]
Current implementation of enable/disable profiling at cluster level hasdrawbacks and really confusing. If `enable` is selected, profiling will be enabled for all volumes - no issues here. But if user choose to disable the profiling, tendrl is will not disable profiling during the import- rather the volumes with prfiling already on stay as is. This is an inconsitency which needs to be fixed. Also cluster wide profiling status doesn't really make any sense because this is property on a volume level. So this is what I propose:

1. Remove cluster wide profiling status.
2. Profiling status to be added at individual volume level.
3. During import provide three options: a) enable b)disable c)no change. Default will be enabled, perform the specific action based on the user action.
4. Provide an action at cluster level to enable/disable profiling for all volumes in the cluster.
5. Provide an action at volume level to enable/disable profiling for individual volumes.

Let me know what you folks think about this - @shtripat , @r0h4n , @julienlim

**Comment by julienlim** [comment]
@nthomas-redhat @shtripat @r0h4n @gnehapk @a2batic @cloudbehl @mcarrano @Tendrl/tendrl-qe @jjkabrown1

(1) Regarding Removing cluster-wide profiling status, as we allow the option of setting this at a cluster level, we should show the status otherwise, how does user get feedback if they set it at a global level.

(2) +1 on including Profiling status at the volume level, i.e. column added to the Volume list view.  I wasn't sure if we're taking RFE's for this at the moment.  Depends on (5) though.

(3) +1.  This has already been discussed widely, and we also suggested the same options.  For reference, see [Tendrl/gluster-integration/Volume profile enabled/not-started info in tendrl #551](https://github.com/Tendrl/gluster-integration/issues/551) which includes the UI design updates in it.

(4) This already exists at the cluster level in the Cluster List.  Do we need another place to make it easier to do this action, similar to launching the Cluster Dashboard?  Or should we wait for user feedback?

(5) +1 on adding this action at the individual volume level.  I wasn't sure if we're taking RFE's for this at the moment.  This goes hand-in-hand with (2) above.

**Comment by nthomas-redhat** [comment]
> (1) Regarding Removing cluster-wide profiling status, as we allow the option of setting this at a cluster level, we should show the status otherwise, how does user get feedback if they set it at a global level.

@julienlim , The concern I have is that even if show at the cluster level, that might not be right always. For example, assume that admin set it to 'enable' globally and we display same. Meantime somebody can go and change certain volume's status to 'disable' as well but the global status will reflect as 'enabled'. Otherwise we need write some logic and construct this status during the sync which is an overhead. I proposed that action at the global level just becase it will make the life easier for admins to set the status of the volumes one shot.

**Comment by julienlim** [comment]
@nthomas-redhat If someone goes and changes it and it's mixed (some volumes profiling enabled and some volumes profiling disabled), the column should say "Mixed."
And, yes you would need to write some logic to check so that it gets presented correctly if we do show the "Volume Profiling" status in the Cluster List.

The bigger question is how critical is it to show this "Volume Profiling" status in the Cluster List?  I'd probably say not critical.  It's a nice-to-have, but if performance is really impacted through the sync to get the Volume Profiling status, then I would agree we can leave out the "Volume Profiling" column in the Cluster List, and we should ensure the docs mention to see details about Volume Profiling status, see that in the Volumes List.

**Comment by shtripat** [comment]
>> yes you would need to write some logic to check so that it gets presented correctly if we do show 
>> the "Volume Profiling" status in the Cluster List.

With new version of gluster, its possible to change the cluster level value as mixed because `get-state` output at every sync time can decide the cluster level value as well. This is doable. But for older version of gluster, `get-state` doesnt provide a detail of profiling so if something changes from CLI, there is no way to detect the changes at volume level and thats why cluster level as well cannot be changed. It would retain the old value which was there for the cluster.

with older version of gluster lets take a scenario -
1. While import cluster user selected `Enable` for volume profiling
2. Once import cluster done the profiling is enabled for all the volumes in the cluster
3. Now suppose admin disables profiling for few volumes from CLI
4. While syncing of the cluster data next time, tendrl finds that cluster level profiling is supposed to be enabled, so it goes ahead and enabled profiling again for all the volumes (volumes already having profiling enabled remain un-affected). This is because while sync there is no way to find that, there is a change in profiling state of volume as get-state doesnt report anything about this.

With newer version of gluster, lets take a scenario
1. User selects `leave as is` for volume profiling
2. Once import done, while syncing the cluster data, get-state returns the individual volume profiling info and based on that cluster level value could be set as `enabled/disabled/mixed`. Even at volume level values change accordingly
3. User selected enable/disable while import, every sync time tendrl makes sure all the volumes reflect the profiling state based on this option selected while import. So even if admin disables profiling for say few volumes, if cluster level it was told to enable profiling while import, next sync would enable for all the volumes again.

Hope things are clearer now regarding both old and new versions of gluster.

@julienlim @nthomas-redhat comments?

**Comment by julienlim** [comment]
@shtripat Looks good.  Thanks for making it clear to all.

**Comment by shtripat** [comment]
With latest changes (PRs under review) the import cluster request looks as below 

```
POST /clusters/{int-id}/import

{"Cluster.volume_profiling_flag": "leave-as-is/enable/disable"}
```

The new entity structure for cluster contains field `volume_profiling_flag` and `volume_profiling_state` and UI should use the field `volume_profiling_state` to show overall volume profiling state at cluster level. The other field `volume_profiling_flag` is used while import cluster only.

To enable / disable profiling at volume level below APIs added

```
POST /clusters/{int-id}/volumes/{vol-id}/start_profiling

{"Volume.volname": "<volname>", "Volume.vol_id": "<vol-id>"}
```

```
POST /clusters/{int-id}/volumes/{vol-id}/stop_profiling

{"Volume.volname": "<volname>", "Volume.vol_id": "<vol-id>"}
```

The new entity structure for volume contains fields `profling_enabled`, `current_job` and `locked_by`. The fields `current_job` and `locked_by` should be used for showing the job status for volumes.

@gnehapk @a2batic ^^^

**Comment by nthomas-redhat** [comment]
Ack. Thanks @shtripat
