### ISSUE TITLE
package errors

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/gluster-integration#82]
I've done package check from https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/build/480512/.
All errors should be fixed and it will be great to fix also 3 warnings.
```
$ rpmlint tendrl-gluster-integration-0.0.1-1.el7.centos.noarch.rpm 
tendrl-gluster-integration.noarch: W: incoherent-version-in-changelog 0.0.1-1 ['0.0.1-1.el7.centos', '0.0.1-1.centos']
tendrl-gluster-integration.noarch: E: script-without-shebang /usr/share/tendrl/gluster_integration/tendrl.conf.sample
tendrl-gluster-integration.noarch: W: non-conffile-in-etc /etc/tendrl/gluster_integration_logging.yaml
tendrl-gluster-integration.noarch: W: no-manual-page-for-binary tendrl-gluster-integration
tendrl-gluster-integration.noarch: E: unknown-key RSA#e879b811 (MD5
1 packages and 0 specfiles checked; 2 errors, 3 warnings.

```

**Comment by ktdreyer** [comment]
- [ ] `incoherent-version-in-changelog 0.0.1-1 ['0.0.1-1.el7.centos', '0.0.1-1.centos']` - Recommend we drop all `%changelog` entries, as I have done in [ceph-installer.spec](https://github.com/ceph/ceph-installer/blob/master/ceph-installer.spec.in#L199). The `%changelog` entries only make sense in a downstream package (Fedora or RH product) IMHO.

- [ ] `tendrl-gluster-integration.noarch: E: script-without-shebang` - This is fixed in PR https://github.com/Tendrl/gluster_integration/pull/83

- [ ] `tendrl-gluster-integration.noarch: W: non-conffile-in-etc /etc/tendrl/gluster_integration_logging.yaml` This file should be marked as `%config`. See

- [ ] `tendrl-gluster-integration.noarch: W: no-manual-page-for-binary tendrl-gluster-integration` - This needs a man page.

- [ ] `tendrl-gluster-integration.noarch: E: unknown-key RSA#e879b811 (MD5` False-positive. The system that ran rpmlint needs to trust the Copr GPG key and then this rpmlint error will go away.

**Comment by r0h4n** [comment]
@TimothyAsir any updates?
